In [1]:
import requests
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [42]:
# Input Files (CSV)

minneapolis = "DataFiles/Minneapolis_Crime_Data_2010-2018.csv"
indianapolis = "DataFiles/Indianapolis_Crime_Data_2007-2019.csv"
atlanta = "DataFiles/Atlanta-2009-2018.csv"
dallas = "DataFiles/Dallas_Fort_WorthCrime_Data.csv"
miami = "DataFiles/Miami_Jail_Bookings__May_29_2015_to_current.csv"

# Output Files (CSV)
minne_out = "DataFiles/minneaplis_sorted.csv"
india_out = "DataFiles/indianapolis_sorted.csv"
atlanta_out = "DataFiles/atlanta_sorted.csv"
dallas_out = "DataFiles/dallas_sorted.csv"
miami_out = "DataFiles/miami_sorted.csv"

In [30]:
minne_start_df = pd.read_csv(minneapolis)
# minne_start_df.columns
minne_sorted_df = minne_start_df.loc[:, ["Offense", "Description", "Description", "Offense", "BeginDate","Time", "UCRCode", "X", "Y"]]
minne_sorted_df.head(20)

,Offense,Description,Description,Offense,BeginDate,Time,UCRCode,X,Y
0,SHOPLF,Shoplifting,Shoplifting,SHOPLF,2010-01-25T20:25:00.000Z,20:25:00,7,-1.038018e+07,5.613397e+06
1,BURGD,Burglary Of Dwelling,Burglary Of Dwelling,BURGD,2010-01-25T07:10:00.000Z,07:10:00,6,-1.038684e+07,5.627201e+06
2,BURGB,Burglary Of Business,Burglary Of Business,BURGB,2010-01-22T17:00:00.000Z,17:00:00,6,-1.038193e+07,5.611276e+06
3,ASLT3,Aslt-sgnfcnt Bdly Hm,Aslt-sgnfcnt Bdly Hm,ASLT3,2010-01-25T17:53:00.000Z,17:53:00,5,-1.038131e+07,5.613960e+06
4,AUTOTH,Motor Vehicle Theft,Motor Vehicle Theft,AUTOTH,2010-01-25T11:00:00.000Z,11:00:00,8,-1.038421e+07,5.621383e+06
5,BURGD,Burglary Of Dwelling,Burglary Of Dwelling,BURGD,2010-01-21T07:00:00.000Z,07:00:00,6,-1.037769e+07,5.611872e+06
6,ROBBIZ,Robbery Of Business,Robbery Of Business,ROBBIZ,2010-01-25T21:10:00.000Z,21:10:00,4,-1.038237e+07,5.615509e+06
7,THEFT,Other Theft,Other Theft,THEFT,2010-01-25T22:09:00.000Z,22:09:00,7,-1.038579e+07,5.618062e+06
8,TFMV,Theft From Motr Vehc,Theft From Motr Vehc,TFMV,2010-01-25T21:00:00.000Z,21:00:00,7,-1.038477e+07,5.615791e+06
9,ROBPAG,Robbery Per Agg,Robbery Per Agg,ROBPAG,2010-01-25T21:38:00.000Z,21:38:00,4,-1.038436e+07,5.612288e+06
10,ROBPAG,Robbery Per Agg,Robbery Per Agg,ROBPAG,2010-01-25T22:36:00.000Z,22:36:00,4,-1.038478e+07,5.614666e+06
11,ROBPAG,Robbery Per Agg,Robbery Per Agg,ROBPAG,2010-01-25T22:20:00.000Z,22:20:00,4,-1.038521e+07,5.613118e+06
12,BURGD,Burglary Of Dwelling,Burglary Of Dwelling,BURGD,2010-01-25T14:00:00.000Z,14:00:00,6,-1.037843e+07,5.607344e+06
13,BURGD,Burglary Of Dwelling,Burglary Of Dwelling,BURGD,2010-01-25T07:45:00.000Z,07:45:00,6,-1.038811e+07,5.627628e+06
14,BURGD,Burglary Of Dwelling,Burglary Of Dwelling,BURGD,2010-01-25T16:00:00.000Z,16:00:00,6,-1.038679e+07,5.605040e+06
15,ROBPER,Robbery Of Person,Robbery Of Person,ROBPER,2010-01-25T22:00:00.000Z,22:00:00,4,-1.038167e+07,5.613667e+06
16,ROBPAG,Robbery Per Agg,Robbery Per Agg,ROBPAG,2010-01-25T22:45:00.000Z,22:45:00,4,-1.037752e+07,5.616924e+06
17,AUTOTH,Motor Vehicle Theft,Motor Vehicle Theft,AUTOTH,2010-01-25T20:00:00.000Z,20:00:00,8,-1.038308e+07,5.615948e+06
18,ROBPAG,Robbery Per Agg,Robbery Per Agg,ROBPAG,2010-01-26T00:50:00.000Z,00:50:00,4,-1.037849e+07,5.613398e+06
19,AUTOTH,Motor Vehicle Theft,Motor Vehicle Theft,AUTOTH,2010-01-25T22:00:00.000Z,22:00:00,8,-1.038180e+07,5.609601e+06

In [31]:
india_start_df = pd.read_csv(indianapolis)
# india_start_df.columns
india_sorted_df = india_start_df.loc[:, ["CRIME", "DATE_","TIME", "UCR", "X_COORD", "Y_COORD"]]
india_sorted_df.head(20)

,CRIME,DATE_,TIME,UCR,X_COORD,Y_COORD
0,CRIMINAL HOMICIDE,2007-01-01T00:00:00.000Z,04:24,110,197257.63,1665903.64
1,CRIMINAL HOMICIDE,2007-01-01T00:00:00.000Z,10:39,110,194654.40,1657659.54
2,CRIMINAL HOMICIDE,2007-01-04T00:00:00.000Z,18:01,110,210918.07,1667754.09
3,CRIMINAL HOMICIDE,2007-01-10T00:00:00.000Z,07:06,110,237903.29,1658024.95
4,CRIMINAL HOMICIDE,2007-01-10T00:00:00.000Z,18:19,110,192426.71,1635335.92
5,CRIMINAL HOMICIDE,2007-01-11T00:00:00.000Z,00:01,110,197313.94,1657434.23
6,CRIMINAL HOMICIDE,2007-01-18T00:00:00.000Z,01:00,110,181659.23,1675372.72
7,CRIMINAL HOMICIDE,2007-01-19T00:00:00.000Z,18:40,110,208479.77,1603161.32
8,CRIMINAL HOMICIDE,2007-01-26T00:00:00.000Z,23:15,110,200528.18,1651385.11
9,CRIMINAL HOMICIDE,2007-02-08T00:00:00.000Z,02:43,110,206124.87,1653093.32
10,CRIMINAL HOMICIDE,2007-02-12T00:00:00.000Z,21:42,110,166290.47,1674644.96
11,CRIMINAL HOMICIDE,2007-02-17T00:00:00.000Z,10:34,110,200043.11,1640822.34
12,CRIMINAL HOMICIDE,2007-02-17T00:00:00.000Z,21:29,110,235539.93,1657099.80
13,CRIMINAL HOMICIDE,2007-02-20T00:00:00.000Z,02:10,110,203644.08,1659802.76
14,CRIMINAL HOMICIDE,2007-02-21T00:00:00.000Z,03:00,110,206325.82,1647015.17
15,CRIMINAL HOMICIDE,2007-02-22T00:00:00.000Z,17:30,110,161084.24,1641690.49
16,CRIMINAL HOMICIDE,2007-02-22T00:00:00.000Z,17:30,110,161084.24,1641690.49
17,CRIMINAL HOMICIDE,2007-02-23T00:00:00.000Z,20:02,110,200982.31,1648436.60
18,CRIMINAL HOMICIDE,2007-02-23T00:00:00.000Z,20:02,110,200982.31,1648436.60
19,CRIMINAL HOMICIDE,2007-02-26T00:00:00.000Z,19:42,110,169360.52,1627921.28

In [29]:
atlanta_start_df = pd.read_csv(atlanta)
# atlanta_start_df.columns
atlanta_sorted_df = atlanta_start_df.loc[:, ["UCR Literal", "Report Date","Occur Time", "UCR #", "Latitude", "Longitude"]]
atlanta_sorted_df.head(20)

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

             UCR Literal Report Date  Occur Time  UCR #  Latitude  Longitude
0    LARCENY-NON VEHICLE  2009-01-01        1145    630  33.68845  -84.49328
1    LARCENY-NON VEHICLE  2009-01-01        1330    630  33.75320  -84.39201
2    LARCENY-NON VEHICLE  2009-01-01        1500    630  33.75735  -84.50282
3    LARCENY-NON VEHICLE  2009-01-01        1450    630  33.84676  -84.36212
4    LARCENY-NON VEHICLE  2009-01-01        1600    630  33.68677  -84.49773
5    LARCENY-NON VEHICLE  2009-01-01        1645    630  33.75786  -84.34875
6    LARCENY-NON VEHICLE  2009-01-01        1740    630  33.70827  -84.45385
7    LARCENY-NON VEHICLE  2009-01-01        1627    630  33.84676  -84.36212
8    LARCENY-NON VEHICLE  2009-01-01         815    630  33.68841  -84.48742
9   LARCENY-FROM VEHICLE  2009-01-01        2000    640  33.76269  -84.39702
10  LARCENY-FROM VEHICLE  2009-01-01        2300    640  33.75902  -84.33120
11  LARCENY-FROM VEHICLE  2009-01-01        2230    640  33.75441  -84.32465
12  LARCENY-FROM VEHICLE  2009-01-01         100    640  33.71464  -84.43612
13  LARCENY-FROM VEHICLE  2009-01-01        2030    640  33.85115  -84.37944
14  LARCENY-FROM VEHICLE  2009-01-01         130    640  33.76675  -84.34595
15  LARCENY-FROM VEHICLE  2009-01-01         900    640  33.75283  -84.36687
16  LARCENY-FROM VEHICLE  2009-01-01        1915    640  33.78080  -84.37334
17  LARCENY-FROM VEHICLE  2009-01-01        1900    640  33.77023  -84.38815
18  LARCENY-FROM VEHICLE  2009-01-01        1700    640  33.78663  -84.38139
19  LARCENY-FROM VEHICLE  2009-01-01        1700    640  33.77917  -84.36851

In [32]:
dallas_start_df = pd.read_csv(dallas)
# dallas_start_df.columns
dallas_sorted_df = dallas_start_df.loc[:, ["Description", "Nature Of Call", "Reported Date", "Location"]]
dallas_sorted_df.head(20)

,Description,Nature Of Call,Reported Date,Location
0,GC 080 Public Intoxication 90E DRUNKENNESS 000...,PUBLIC INTOXICATION,08/09/2019,NaN
1,PC 30.03 Burglary Coin Oper Col Machine 23E THEFT,BURGLARY COIN,05/09/2019,"(32.724915021438086, -97.41403442866837)"
2,PC 30.02(C)(2) Burglary Habitation 220 BURGLAR...,BURGLARY RESIDENTIAL,11/17/2016,"(32.76230775795685, -97.39014722478377)"
3,PC 32.51 Fraud Use Poss of ID Info 26F Identit...,FRAUD,12/11/2018,"(32.76088022312888, -97.34294560089083)"
4,PC 22.01(A)(1) Assault Causes B/I 13B SIMPLE A...,ASSAULT,10/24/2018,"(32.71732110345178, -97.35193318230765)"
5,PC 31.03 - Others Theft - Others 23H ALL OTHER...,THEFT,11/01/2018,"(32.862747162683725, -97.31437655021762)"
6,HSC 481.117(B) Poss CS PG 3 <28G 35A DRUG/NARC...,NARCOTIC VIOLATIONS,10/01/2018,"(32.79635361217594, -97.38815742340216)"
7,PC 31.03 - Others Theft - Others 23H ALL OTHER...,THEFT,10/01/2018,"(32.63958939377861, -97.40279649628718)"
8,PC 31.03 (F) Theft Prop<$2500 2+Conv ENH IAT 23H,THEFT,10/01/2018,"(32.738526650414045, -97.33934914830031)"
9,PC 22.01 (C)(1) Aslt Against Elderly/Disabled Ind,ASSAULT,11/09/2018,"(32.749879811444416, -97.33027504684337)"
10,CCP 62.10(B)(3) FAIL TO COMPLY SEX OFF DUTY TO...,SEX REGISTRATION,07/08/2019,"(32.71937978117943, -97.2743658108235)"
11,PC 30.04(A) Burglary Vehicle 23F THEFT FROM MOTOR,BURGLARY VEHICLE COMMERCI,10/01/2018,"(32.738781129461046, -97.25779355098044)"
12,GC 514 Graffiti - Private Property 290 DESTRUC...,GRAFFITI,10/02/2018,"(32.804854289861716, -97.35155770852529)"
13,GC 109 Consume Alcohol Where Prohibited 90G LI...,CITY ORDINANCES,10/02/2018,"(32.74623052100652, -97.31576032982986)"
14,HSC 481.115(B) Poss CS PG 1 <1G 35A DRUG/NARCOTIC,NARCOTIC VIOLATIONS,03/22/2019,"(32.68500850436027, -97.3318060804058)"
15,PC 30.05(A) Criminal Trespass 90J TRESPASS OF ...,NARCOTIC VIOLATIONS,03/22/2019,"(32.68500850436027, -97.3318060804058)"
16,LOCAL Local Class C Warrants 90Z ALL OTHER OFF...,NARCOTIC VIOLATIONS,03/22/2019,"(32.68500850436027, -97.3318060804058)"
17,PC 19.02 Murder Under Influen Sudden Pass 09A ...,MURDER,04/21/2018,"(32.82332638428622, -97.37977746472109)"
18,GC 085-07 Theft under $100 23C SHOPLIFTING 000...,THEFT,10/18/2018,"(32.76254182186685, -97.17124763884867)"
19,PC 32.31 Credit/Debit Card Abuse 26B FRAUD CREDIT,FRAUD,10/02/2018,"(32.64837295401354, -97.32162534057147)"

In [39]:
miami_start_df = pd.read_csv(miami)
# miami_start_df.columns
miami_sorted_df = miami_start_df.loc[:, ["Charge1", "ChargeCode1", "BookDate", "Zip1"]]
miami_sorted_df.head(20)

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

                 Charge1 ChargeCode1                  BookDate       Zip1
0                BATTERY     7840300  2015-06-16T04:00:00.000Z  331436901
1   DOM VIO/INJ VIOLATIO         NaN  2015-06-16T04:00:00.000Z  331657744
2    CANN/TRF/25-2000LBS  89313501A1  2015-06-16T04:00:00.000Z      33165
3                    NaN         NaN  2015-06-16T04:00:00.000Z  331754816
4                    NaN         NaN  2015-06-16T04:00:00.000Z      33167
5          BENCH WARRANT         NaN  2015-06-16T04:00:00.000Z      33167
6                BATTERY     7840300  2015-06-16T04:00:00.000Z      33189
7   NO VALID DRIVERS LIC    32203001  2015-06-16T04:00:00.000Z      33127
8         CRIM MIS/0-200  80613001B1  2015-06-16T04:00:00.000Z  330234768
9         DWLS/KNOWINGLY    32234002  2015-06-16T04:00:00.000Z  331693033
10  MR 2D/LEO/AT/DW/FA/B   78204002L  2015-06-16T04:00:00.000Z  331472542
11        ARREST WARRANT         NaN  2015-06-16T04:00:00.000Z      33126
12          ALIAS CAPIAS         NaN  2015-06-16T04:00:00.000Z  331415825
13   PROBATION VIOLATION    94806101  2015-06-16T04:00:00.000Z  330331852
14  ALC BEV/DRK IN PUBLC     0040100  2015-06-16T04:00:00.000Z        NaN
15         BENCH WARRANT         NaN  2015-06-16T04:00:00.000Z      33010
16     INDECENT EXPOSURE     8000300  2015-06-16T04:00:00.000Z  330131461
17    WRIT/BODILY ATTACH     9960010  2015-06-16T04:00:00.000Z      33165
18     PROBATION WARRANT         NaN  2015-06-16T04:00:00.000Z      33174
19  TRES PROP/AFTER WARN  81009001A1  2015-06-16T04:00:00.000Z        NaN

In [41]:
# minne_start_df.head(10)
# india_start_df.head(10)
# atlanta_start_df.head(10)
# dallas_start_df.head(10)
# miami_start_df.head(10)

# Export DataFrame to csv file
weather_df.to_csv(weather_data_csv)

In [43]:
# Export DataFrame to csv file
minne_sorted_df.to_csv(minne_out)
india_sorted_df.to_csv(india_out)
atlanta_sorted_df.to_csv(minne_out)
minne_sorted_df.to_csv(minne_out)
minne_sorted_df.to_csv(minne_out)