In [1]:
#Dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook

In [3]:
#Read crime csv
ny_df = pd.read_csv("NY_Crime_Data_Filtered_New.csv")
ny_df.head()

,Unnamed: 0,CMPLNT_FR_DT,OFNS_DESC,LAW_CAT_CD,PD_DESC,Month,Day,Year
0,0,2016-12-31,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,ASSAULT 3,12,31,2016
1,1,2016-12-31,HARRASSMENT 2,VIOLATION,"HARASSMENT,SUBD 1,CIVILIAN",12,31,2016
2,2,2016-12-31,CRIMINAL MISCHIEF & RELATED OF,MISDEMEANOR,"CRIMINAL MISCHIEF 4TH, GRAFFIT",12,31,2016
3,3,2016-12-31,PETIT LARCENY,MISDEMEANOR,"LARCENY,PETIT BY DISHONEST EMP",12,31,2016
4,4,2016-12-31,OFF. AGNST PUB ORD SENSBLTY &,MISDEMEANOR,AGGRAVATED HARASSMENT 2,12,31,2016

In [4]:
#Converting date to datetime
ny_df['CMPLNT_FR_DT'] = pd.to_datetime(ny_df['CMPLNT_FR_DT'])

In [5]:
# Combining types of crimes
ny_df = ny_df.replace({"OFF.AGNST PUB ORD SENSBLTY &": "Criminal Mischief", "CRIMINAL MISCHIEF & RELATED OF": "Criminal Mischief",\
                      "DISORDERLY CONDUCT": "Criminal Mischief", "OFFENSES AGAINST PUBLIC SAFETY": "Criminal Mischief", "PETIT LARCENY":\
                      "Theft", "INTOXICATED & IMPAIRED DRIVING": "Impaired Driving", "GRAND LARCENY OF MOTOR VEHICLE": "Vehicle Theft",\
                      "ASSAULT 3 & RELATED OFFENSES": "Assault", "PROSTITUTION & RELATED OFFENSES": "Prostitution"})

ny_df.head(25)

,Unnamed: 0,CMPLNT_FR_DT,OFNS_DESC,LAW_CAT_CD,PD_DESC,Month,Day,Year
0,0,2016-12-31,Assault,MISDEMEANOR,ASSAULT 3,12,31,2016
1,1,2016-12-31,HARRASSMENT 2,VIOLATION,"HARASSMENT,SUBD 1,CIVILIAN",12,31,2016
2,2,2016-12-31,Criminal Mischief,MISDEMEANOR,"CRIMINAL MISCHIEF 4TH, GRAFFIT",12,31,2016
3,3,2016-12-31,Theft,MISDEMEANOR,"LARCENY,PETIT BY DISHONEST EMP",12,31,2016
4,4,2016-12-31,OFF. AGNST PUB ORD SENSBLTY &,MISDEMEANOR,AGGRAVATED HARASSMENT 2,12,31,2016
5,5,2016-12-31,Theft,MISDEMEANOR,"LARCENY,PETIT FROM BUILDING,UN",12,31,2016
6,6,2016-12-31,BURGLARY,FELONY,"BURGLARY,RESIDENCE,UNKNOWN TIM",12,31,2016
7,7,2016-12-31,Assault,MISDEMEANOR,ASSAULT 3,12,31,2016
8,8,2016-12-31,Criminal Mischief,MISDEMEANOR,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",12,31,2016
9,9,2016-12-31,Theft,MISDEMEANOR,"LARCENY,PETIT FROM STORE-SHOPL",12,31,2016
10,10,2016-12-31,HARRASSMENT 2,VIOLATION,"HARASSMENT,SUBD 3,4,5",12,31,2016
11,11,2016-12-31,ROBBERY,FELONY,"ROBBERY,OPEN AREA UNCLASSIFIED",12,31,2016
12,12,2016-12-31,Theft,MISDEMEANOR,"LARCENY,PETIT FROM STORE-SHOPL",12,31,2016
13,13,2016-12-31,DANGEROUS DRUGS,MISDEMEANOR,"CONTROLLED SUBSTANCE, POSSESSI",12,31,2016
14,14,2016-12-31,Theft,MISDEMEANOR,"LARCENY,PETIT FROM AUTO",12,31,2016
15,15,2016-12-31,HARRASSMENT 2,VIOLATION,"HARASSMENT,SUBD 3,4,5",12,31,2016
16,16,2016-12-31,FELONY ASSAULT,FELONY,"ASSAULT 2,1,UNCLASSIFIED",12,31,2016
17,17,2016-12-31,Theft,MISDEMEANOR,"LARCENY,PETIT FROM BUILDING,UN",12,31,2016
18,18,2016-12-31,Theft,MISDEMEANOR,"LARCENY,PETIT BY DISHONEST EMP",12,31,2016
19,19,2016-12-31,Theft,MISDEMEANOR,"LARCENY,PETIT FROM STORE-SHOPL",12,31,2016
20,20,2016-12-31,Impaired Driving,MISDEMEANOR,"INTOXICATED DRIVING,ALCOHOL",12,31,2016
21,21,2016-12-31,HARRASSMENT 2,VIOLATION,"HARASSMENT,SUBD 1,CIVILIAN",12,31,2016
22,22,2016-12-31,Theft,MISDEMEANOR,"LARCENY,PETIT BY ACQUIRING LOS",12,31,2016
23,23,2016-12-31,HARRASSMENT 2,VIOLATION,"HARASSMENT,SUBD 3,4,5",12,31,2016
24,24,2016-12-31,Criminal Mischief,MISDEMEANOR,"MISCHIEF, CRIMINAL 4, OF MOTOR",12,31,2016

In [8]:
# Passing OFNS_DESC items into series to be filtered out
ny_df_filtered = ny_df[ny_df.OFNS_DESC.isin(["Criminal Mischief", "Theft", "Impaired Driving", "Prostitution", "Assault",\
                                            "Vehicle Theft"])]
ny_df_filtered.tail(25)

,Unnamed: 0,CMPLNT_FR_DT,OFNS_DESC,LAW_CAT_CD,PD_DESC,Month,Day,Year
1937892,1937892,2013-01-01,Criminal Mischief,MISDEMEANOR,"MISCHIEF, CRIMINAL 4, OF MOTOR",1,1,2013
1937893,1937893,2013-01-01,Criminal Mischief,MISDEMEANOR,"CRIMINAL MISCHIEF 4TH, GRAFFIT",1,1,2013
1937894,1937894,2013-01-01,Criminal Mischief,MISDEMEANOR,"CRIMINAL MISCHIEF 4TH, GRAFFIT",1,1,2013
1937897,1937897,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013
1937899,1937899,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013
1937905,1937905,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013
1937906,1937906,2013-01-01,Criminal Mischief,MISDEMEANOR,"CRIMINAL MISCHIEF 4TH, GRAFFIT",1,1,2013
1937907,1937907,2013-01-01,Criminal Mischief,MISDEMEANOR,"CRIMINAL MISCHIEF 4TH, GRAFFIT",1,1,2013
1937910,1937910,2013-01-01,Criminal Mischief,MISDEMEANOR,"CRIMINAL MISCHIEF 4TH, GRAFFIT",1,1,2013
1937914,1937914,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013
1937917,1937917,2013-01-01,Assault,MISDEMEANOR,OBSTR BREATH/CIRCUL,1,1,2013
1937924,1937924,2013-01-01,Criminal Mischief,MISDEMEANOR,"CRIMINAL MISCHIEF 4TH, GRAFFIT",1,1,2013
1937926,1937926,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013
1937929,1937929,2013-01-01,Criminal Mischief,MISDEMEANOR,"CRIMINAL MISCHIEF 4TH, GRAFFIT",1,1,2013
1937931,1937931,2013-01-01,Criminal Mischief,FELONY,"MISCHIEF, CRIMINAL 3 & 2, OF M",1,1,2013
1937933,1937933,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013
1937936,1937936,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013
1937940,1937940,2013-01-01,Impaired Driving,MISDEMEANOR,"INTOXICATED DRIVING,ALCOHOL",1,1,2013
1937941,1937941,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013
1937942,1937942,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013
1937943,1937943,2013-01-01,Criminal Mischief,MISDEMEANOR,"MISCHIEF, CRIMINAL 4, OF MOTOR",1,1,2013
1937944,1937944,2013-01-01,Criminal Mischief,MISDEMEANOR,"CRIMINAL MISCHIEF 4TH, GRAFFIT",1,1,2013
1937945,1937945,2013-01-01,Impaired Driving,MISDEMEANOR,"INTOXICATED DRIVING,ALCOHOL",1,1,2013
1937948,1937948,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013
1937954,1937954,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013

In [11]:
#Filtering dates for first graph: Jan-Feb 2013
ny_df_2013_filter = ny_df_filtered[ny_df_filtered['CMPLNT_FR_DT']>="01/01/2013"]
ny_df_2013_filter.tail()

,Unnamed: 0,CMPLNT_FR_DT,OFNS_DESC,LAW_CAT_CD,PD_DESC,Month,Day,Year
1937943,1937943,2013-01-01,Criminal Mischief,MISDEMEANOR,"MISCHIEF, CRIMINAL 4, OF MOTOR",1,1,2013
1937944,1937944,2013-01-01,Criminal Mischief,MISDEMEANOR,"CRIMINAL MISCHIEF 4TH, GRAFFIT",1,1,2013
1937945,1937945,2013-01-01,Impaired Driving,MISDEMEANOR,"INTOXICATED DRIVING,ALCOHOL",1,1,2013
1937948,1937948,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013
1937954,1937954,2013-01-01,Assault,MISDEMEANOR,ASSAULT 3,1,1,2013

In [12]:
# Filtering date: nothing after Feb 28, 2013
ny_df_feb_2013 = ny_df_2013_filter[ny_df_2013_filter['CMPLNT_FR_DT']<="02/28/2013"]
ny_df_feb_2013.head()

,Unnamed: 0,CMPLNT_FR_DT,OFNS_DESC,LAW_CAT_CD,PD_DESC,Month,Day,Year
1863369,1863369,2013-02-28,Criminal Mischief,MISDEMEANOR,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",2,28,2013
1863371,1863371,2013-02-28,Theft,MISDEMEANOR,"LARCENY,PETIT BY ACQUIRING LOS",2,28,2013
1863372,1863372,2013-02-28,Assault,MISDEMEANOR,ASSAULT 3,2,28,2013
1863373,1863373,2013-02-28,Assault,MISDEMEANOR,ASSAULT 3,2,28,2013
1863376,1863376,2013-02-28,Assault,MISDEMEANOR,ASSAULT 3,2,28,2013

In [13]:
ny_df_feb_2013.count()

Unnamed: 0      28699
CMPLNT_FR_DT    28699
OFNS_DESC       28699
LAW_CAT_CD      28699
PD_DESC         28699
Month           28699
Day             28699
Year            28699
dtype: int64

In [ ]:
#Line Graph for New York Crimes Jan-Feb 2013 (Year Before Superbowl)

# Variables